### ISSUE TITLE
メソッド名の変更

### ISSUE THREAD

**Issue by stgctkm** [somurieengieer/ddd-training#11]
https://github.com/somurieengieer/ddd-training/blob/master/src/com/example/domain/%E6%99%82%E6%9C%9F.java#L12

メソッド名は全て同じで、引数の型の違いで呼び分けられます。

```
宿泊料金 大人ひとり1泊の料金(繁忙期 season) {}
宿泊料金 大人ひとり1泊の料金(閑散期 season) {}
...
```

**Comment by somurie06** [comment]
enumの値で呼び分けできるんですか。
調べても発見まで至りませんでした（悔しい）

**Comment by somurie06** [comment]
すみません、繁忙期・閑散期はEnumの値ではなくてclassである前提ですの指摘ですか？
（同じメソッド名に対してenumの値を引数にして分けるのは無理ですよね？発見できませんでした）

繁忙期・閑散期などはclassにしようかと思ったのですがenumの方がファイル数が少なくて整理が楽そうであったためenumにしてみました。
ロジックについてはclassでもenumでもOpenClosedの原則に基づいて作れると思っていますが、classにする利点はありますか？

**Comment by stgctkm** [comment]
ごめんなさい。
Enumだったのですね。
できないですね。

**Comment by somurie06** [comment]
Enumで試してみました。
一旦このままにしておきます。

**Comment by stgctkm** [comment]
> enumの方がファイル数が少なくて

ファイルの数はむしろ多い方が整理できますよ。
１つ１つのファイル（クラス）の責務が小さくなるので、わかりやすくなるはずです。

クラス図にしたときに、業務ルールがイメージできるようになるはずです。

**Comment by somurie06** [comment]
確かに、ファイル単位で責務が小さくなりますね。
クラス図にした時に差がでるのも納得です。

**Comment by somurie06** [comment]
マージしましたのでクローズします。
他に気になる点がありましたらリオープン願います。
